name: airbnb-price-regression
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipykernel
  - pathlib
  - loguru
  - pip
  - pip:
    - pydantic
    - pytest
    - xgboost
    - mlflow
    - fastapi
    - uvicorn
    - streamlit